name: interest_compound_game
description: Juego educativo de interés compuesto con Flutter + Flame
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.8.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
