// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfAFbu5yo03BS8CbdUP2WFcSxYrpNnlic',
    appId: '1:389793525566:web:8bdce35f7a1b1ccddcc66f',
    messagingSenderId: '389793525566',
    projectId: 'flutter-interes',
    authDomain: 'flutter-interes.firebaseapp.com',
    storageBucket: 'flutter-interes.firebasestorage.app',
    measurementId: 'G-GPWK83NGWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBls1eU5bSIjC0S1UpfLNOXDp9_ZeneP6A',
    appId: '1:389793525566:android:0e5588f5c11a57bedcc66f',
    messagingSenderId: '389793525566',
    projectId: 'flutter-interes',
    storageBucket: 'flutter-interes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxzQZT4Fq5xfBkgeLhYgbX3w2q8ULiqf0',
    appId: '1:389793525566:ios:2aaec4e0268e19b9dcc66f',
    messagingSenderId: '389793525566',
    projectId: 'flutter-interes',
    storageBucket: 'flutter-interes.firebasestorage.app',
    iosBundleId: 'com.example.interestCompoundGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxzQZT4Fq5xfBkgeLhYgbX3w2q8ULiqf0',
    appId: '1:389793525566:ios:2aaec4e0268e19b9dcc66f',
    messagingSenderId: '389793525566',
    projectId: 'flutter-interes',
    storageBucket: 'flutter-interes.firebasestorage.app',
    iosBundleId: 'com.example.interestCompoundGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfAFbu5yo03BS8CbdUP2WFcSxYrpNnlic',
    appId: '1:389793525566:web:900e511fea35d51fdcc66f',
    messagingSenderId: '389793525566',
    projectId: 'flutter-interes',
    authDomain: 'flutter-interes.firebaseapp.com',
    storageBucket: 'flutter-interes.firebasestorage.app',
    measurementId: 'G-6R25FSQQCR',
  );
}
